names:
- crack
- scratch
- pit
- inclusion
- oxidation
- stain
nc: 6
path: C:\Users\20492\Desktop\project\industrial-defect-detection
train: C:\Users\20492\Desktop\project\industrial-defect-detection\data\augmented\train\images
val: C:\Users\20492\Desktop\project\industrial-defect-detection\data\raw\val\images
